### ISSUE TITLE
LV2 testing?

### ISSUE THREAD

**Issue by mxmilkiib** [CrushedPixel/Plugalyzer#1]
With the forthcoming LV2-hosting in JUCE, how about LV2?

**Comment by CrushedPixel** [comment]
I haven't previously heard of LV2, but absolutely! This should be as simple as adding the preprocessor definition to enable plugin host support for LV2 to the `CMakeLists.txt`: https://github.com/CrushedPixel/Plugalyzer/blob/main/CMakeLists.txt#L27

Feel free to ping me again when JUCE 7 is out and this feature is added.

**Comment by CrushedPixel** [comment]
@mxmilkiib I'm very tight on time right now, would you be willing to make a PR that updates this project to JUCE 7 and adds the LV2 flag?
