### ISSUE TITLE
ERROR - License checking thread exiting

### ISSUE THREAD

**Issue by direr-lower** [CrushedPixel/Plugalyzer#14]
When I first installed Plugalyzer I was able to process a wav file using a plugin. A few weeks later, I'm getting this error "License checking thread exiting" when trying to run. I can use the VST3 plugin within Amadeus Pro and Audacity so it is licensed to this computer. What is this error and how do I get it to go away so I can process my files again?

**Comment by CrushedPixel** [comment]
This is a plug-in specific issue. I don’t know which plug-in you’re using and how its license protection mechanism works, so I can’t help you any further. Even with that information, I’m not sure if there’s anything that can be done about it without opening a GUI and entering credentials, which is out of scope for this software.

The intention of Plugalyzer is mainly to test your own plug-ins without having to run an entire DAW, so this is an unfortunate incompatibility that’s out of scope for us to fix.

**Comment by direr-lower** [comment]
Thank you for the quick reply. It does seem to be plug-in specific because I can run other plugins with no error. It's just strange that it worked a few weeks ago when first installing and now it doesn't. Can you point me to where within the MacOS Plugalyzer checks to see if a license is registered? What file it's looking for?  Maybe that could help me to further diagnose the issue.

**Comment by CrushedPixel** [comment]
As I said, Plugalyzer doesn’t do anything for license checking, it only hosts the audio plug-in. All license checking code, including the error message you get, comes from the plug-in you’re running and Plugalyzer has no control about it whatsoever. I’m afraid there’s nothing you can do short of contacting the plug-in manufacturer and asking them about this problem.

**Comment by direr-lower** [comment]
Is there way I can make a donation?
