### ISSUE TITLE
FTXUI support?

### ISSUE THREAD

**Issue by godofecht** [CrushedPixel/Plugalyzer#22]
Given that tools like FTXUI exist to enable user interactivity FROM the command line, it shouldn't really be difficult to iterate through plugin parameters and pipe values into the callback.

I think this would be a neat feature... Could combine efforts. Or not?

**Comment by CrushedPixel** [comment]
Hey Abhishek, nice to hear from you. Can you give a more detailed explanation on what the goal/use case for this would be?

Also, I do not intend to invest significant effort into this tool. I will more than happily review and accept PRs though.

**Comment by godofecht** [comment]
I'd like to be able to spin up an interactive interface directly from the
command line, to modify parameters within a real-time audio callback.

This would help facilitate real time plugin testing outside of the DAW.

"Command Line VST Host" is what I'm thinking about. Honestly, it might make
sense to create a separate repo for that.

**Comment by CrushedPixel** [comment]
I agree that this should be a separate project.
