### ISSUE TITLE
Support for MIDI input files 

### ISSUE THREAD

**Issue by sudara** [CrushedPixel/Plugalyzer#4]
I'm building a synth and this is on my list of tools to make for QA/CI for phase cancellation regression testing.

I'd be happy to help if you'd prefer a contribution.

**Comment by CrushedPixel** [comment]
This should be pretty trivial to do, and is of course a feature I'd love to see - matter of fact, I left a respective TODO in the codebase when I initially wrote this tool a few days ago 😋

This is super trivial to implement (famous last words, I know), so I'll give it a shot right now!
