### ISSUE TITLE
Take an `--input-file` to run plugalyzer over a list of inputs 

### ISSUE THREAD

**Issue by sudara** [CrushedPixel/Plugalyzer#9]
👋

Some greedy scope creep here:

I'd like to provide plugalyzer with a newline separated file of inputs (and their parameter file inputs?), something like:

```
path/to/input1.mid path/to/parameters1.json
path/to/input2.mid path/to/parameters2.json
```

Plugalyzer would then iterate over each, creating one output file per line.

For now I will just run an instance of plugalyzer per-input!

**Comment by CrushedPixel** [comment]
I don't see the benefit over running `plugalyzer` multiple times. Instead of adding yet another input format, just use what the CLI gives you!
